const countryNames = {
  US: "United States", GB: "United Kingdom", CA: "Canada", AU: "Australia",
  DE: "Germany", FR: "France", IT: "Italy", ES: "Spain", NL: "Netherlands",
  SE: "Sweden", NO: "Norway", DK: "Denmark", FI: "Finland", PL: "Poland",
  RU: "Russia", JP: "Japan", CN: "China", IN: "India", BR: "Brazil",
  MX: "Mexico", ZA: "South Africa", KR: "South Korea", SG: "Singapore",
  NZ: "New Zealand", IE: "Ireland", PT: "Portugal", GR: "Greece",
  TR: "Turkey", SA: "Saudi Arabia", AE: "United Arab Emirates",
  TH: "Thailand", MY: "Malaysia", PH: "Philippines", ID: "Indonesia",
  VN: "Vietnam", AR: "Argentina", CL: "Chile", CO: "Colombia",
  PE: "Peru", EC: "Ecuador", CU: "Cuba", CR: "Costa Rica",
  PK: "Pakistan", BD: "Bangladesh", IL: "Israel", EG: "Egypt",
  HK: "Hong Kong", TW: "Taiwan", CH: "Switzerland", AT: "Austria",
  BE: "Belgium", CZ: "Czech Republic", HU: "Hungary", RO: "Romania",
  BG: "Bulgaria", HR: "Croatia", SK: "Slovakia", UA: "Ukraine",
  BY: "Belarus", LT: "Lithuania", LV: "Latvia", EE: "Estonia",
  NG: "Nigeria", KE: "Kenya", GH: "Ghana", ET: "Ethiopia",
  MA: "Morocco", TN: "Tunisia", DZ: "Algeria", LY: "Libya",
  UG: "Uganda", TZ: "Tanzania", MW: "Malawi", ZM: "Zambia",
  ZW: "Zimbabwe", BW: "Botswana", NA: "Namibia", MZ: "Mozambique",
  AO: "Angola", LK: "Sri Lanka", MM: "Myanmar", KH: "Cambodia",
  LA: "Laos", KZ: "Kazakhstan", UZ: "Uzbekistan", TJ: "Tajikistan",
  KG: "Kyrgyzstan", TM: "Turkmenistan", AF: "Afghanistan", IR: "Iran",
  IQ: "Iraq", JO: "Jordan", LB: "Lebanon", SY: "Syria",
  AQ: "Antarctica", FJ: "Fiji", SB: "Solomon Islands", VU: "Vanuatu",
  WS: "Samoa", TO: "Tonga", KI: "Kiribati", MH: "Marshall Islands",
  PW: "Palau", FM: "Micronesia", NR: "Nauru", TV: "Tuvalu",
  PR: "Puerto Rico", DO: "Dominican Republic", JM: "Jamaica",
  TT: "Trinidad and Tobago", BB: "Barbados", BS: "Bahamas",
  AG: "Antigua and Barbuda", LC: "Saint Lucia", GD: "Grenada",
  VC: "Saint Vincent and the Grenadines", DM: "Dominica",
  KN: "Saint Kitts and Nevis", BZ: "Belize", HN: "Honduras",
  SV: "El Salvador", GT: "Guatemala", NI: "Nicaragua", PA: "Panama",
  VE: "Venezuela", GY: "Guyana", SR: "Suriname", GF: "French Guiana",
  BO: "Bolivia", PY: "Paraguay", UY: "Uruguay", UE: "United Arab Emirates",
  QA: "Qatar", BH: "Bahrain", KW: "Kuwait", OM: "Oman",
  YE: "Yemen", AZ: "Azerbaijan", GE: "Georgia", AM: "Armenia",
  LU: "Luxembourg", MT: "Malta", CY: "Cyprus", IS: "Iceland",
  MC: "Monaco", LI: "Liechtenstein", AD: "Andorra", SM: "San Marino",
  VA: "Vatican City", MK: "North Macedonia", AL: "Albania",
  BA: "Bosnia and Herzegovina", ME: "Montenegro", RS: "Serbia",
  SI: "Slovenia"
};

module.exports = countryNames;
